using System;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Security;

//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:2.0.50727.5446
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyVersionAttribute("2.5.0.0")]
[assembly: AssemblyFileVersionAttribute("2.5.0.0")]
[assembly: AssemblyCopyrightAttribute("Copyright Â© NServiceBus 2007-2011")]
[assembly: AssemblyProductAttribute("NServiceBus")]
[assembly: AssemblyCompanyAttribute("NServiceBus")]
[assembly: AssemblyConfigurationAttribute("release")]
[assembly: AssemblyInformationalVersionAttribute("2.5.0.0")]
[assembly: ComVisibleAttribute(false)]

